---
- name: Install Ceph on VMs
  hosts: ceph
  become: true

  tasks:
    - name: Add Ceph repository key
      apt_key:
        url: https://download.ceph.com/keys/release.asc

    - name: Add Ceph repository
      apt_repository:
        repo: "deb http://download.ceph.com/debian-{ceph-stable-release}/ {{ ansible_distribution_release }} main"

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Ceph
      apt:
        name: ceph
        state: present
