# cephadm-config.yaml.tpl

osd:
  count: 2
  hosts:
    - 35.205.242.35
    - 35.187.27.91

mon:
  count: 1
  hosts:
    - 34.77.39.61

mgr:
  count: 1
  hosts:
    - 104.199.12.216

rbd:
  count: 1
  hosts:
    - 34.140.96.221